site_name: Log0c
theme:
  name: readthedocs
  highlightjs: true
#  custom_dir: custom_theme/
  sticky_navigation: false
  hljs_languages:
        - go
plugins:
  #  - markdownmermaid
  - mermaid2
extra_javascript:
  - js/mermaid.min.js
  - js/custom.js
#  - js/highlight.min.js
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
extra_css:
#  - css/extra.css
nav:
  - 主页: index.md
  - 问题排查 :
      - mac 网易云音乐 cpu 占用高问题排查: too-much-folder/netease-music-problem.md
      - mac 外部 SSD Swap 分区开启问题: mac/osx86_external_ssd_swap_problem.md
      - mac Notes.app 卡死问题: mac/mac-note-stalled.md
      - go 使用 pprof 排查内存泄漏: too-much-folder/go-pprof-memory-leak.md
      - go bytebufferpool 错误使用一例: too-much-folder/go-bytebufferpool-leak-doubt.md
      - go shadowing variable 造成的歧义: too-much-folder/go-shadowing-variable.md
      - go 并发读写 map 问题一例: too-much-folder/go-concurrent-map-read-write-bug.md
      - db metadata lock 问题排查: too-much-folder/db-metadatalock.md
      - db 间隙锁造成的死锁: too-much-folder/db-deadlock.md
      - db 复现不同索引之间的死锁: too-much-folder/db-deadlock-2.md
      - io 黑盒排查磁盘空间告警/IO问题: too-much-folder/black-box-io-problem.md
      - cpu 排查的几个案例: too-much-folder/black-box-cpu-high-problem.md
      - network 排查的几个案例: too-much-folder/black-box-network-problem.md
      - network tcp 常见状态异常: too-much-folder/tcp-troubleshooting.md
      - all 问题排查速查表: too-much-folder/troubleshooting-cheatsheet.md


#  - 数据库 simpledb:
#      -

  - 源码阅读:
      - go 源码阅读技巧: too-much-folder/go-doc-reading-technique.md
#      - gdb 汇编 go xv6 函数调用栈 atomic: too-much-folder/gdb.md
#      - singleflight: too-much-folder/go-singleflight.md
      - valyala/bytebufferpool: too-much-folder/go-valyala-bytebufferpool.md
      - atomic LoadInt64 和 LoadInt32 使用疑问: too-much-folder/go-atomic.md
#      - channel 深入实验: too-much-folder/go-channel-in-open-source.md 在 go 并发课学到了很多新模式,实验回顾加深印象
#      - gammazero/workerpool: too-much-folder/go-gammazero-workerpool.md
  #      - valyala/fasthttp: too-much-folder/go-valyala-fasthttp.md


#  -  性能优化/性能测试:
#       - 极客时间课看了再说, 看系统性能调优必知必会 , 再看一门性能测试?: asd.md
#       - go  benchmark 和测试 总结: asd.md

#(复现 , 动手做基准测试 benchmark , 评判优化效果的指标(QPS....) ) :
#      - 使用 stress 和 wrk 复现压测优化过程: dsad.md
          # 基准测试工具速查表  wrk , ab , stress , pktgen , jmeter , iperf
#      - 基准测试工具实践: xxx.md    wrk , ab , stress ,模拟 cpu 模拟内存消耗 模拟网络消耗 io 消耗
#      - singleflight 和 workerpool 优化代码 模拟复现,基准测试 ,看看8c16G 能有多少 qps 内部的某个接口的平均耗时 2s , 最近请求量多了还有超时 , 开始优化 , 模拟 http 每个 200ms , 模拟 mysql , 封装一个 mysql 结构体 , 请求计数, 当并发请求达到 1000 个时耗时增加  , 使用 wrk 和 ab , openresty实战 好像说 wrk 更好: too-much-folder/singleflight-workerpool.md
          # 调试工具 gdb , coredump , objdump

#          - go http client 参数优化: too-much-folder/go-http-client-config.md
#          - zookeeper 对比我的 raft kv 实现: too-much-folder/zookeeper-vs-raft-kv.md
#          - lock-free 队列 vs lock in go  sync.pool
          # docker k8s helm kvm 性能 压测 shell qemu
#          - go http client  在 手把手 web 框架学到的一个读源码的方式 , 实践一下: too-much-folder/go-http-client-dig-deep.md
#          - etcd 的 watch 实现: too-much-folder/etcd-watch.md
#          - 锁在 etcd 中的实现: too-much-folder/etcd-watch.md
          #- workerpool 源码阅读 , fasthttp


#  - 瞎折腾:
          #        - 一台现代公路车的构成: sport/modern-bicycle-composition.md
          #        - 如何跑步: sport/run-the-right-way.md
          #        - 作为一个懒人如何跟上饮食: sport/eat.md
          #        - 深圳爬坡路线汇总: sport/shenzhen-mountain.md
          #        - 手残党如何打上 LOL 钻石: sport/lol-diamond.md


          # 延后
            #          - atomic 在 go 中的使用  , 为什么用了? 因为 int64 操作可能不是原子的
            #          - 连接池使用注意事项: too-much-folder/tcp-linux-config.md
#  -  算法 用问题排查和性能优化的角度做 :
          #      - 问题排查常用工具的实现原理: too-much-folder/troubleshooting-tools-dig-deep.md
          #  - 重要提醒记录: too-much-folder/important-phase.md

          # step: golox , simpledb , xv6 , zk , etcd , and others
          #  - sports
          #      - bicycle Yinhu Mountain 15KM/H
          #      - bao'an park 10KM , 6 minute/km
          #  - 其他:
          #      - can write syscall be interrupted ?: /asd.md
          #      - 文件管理的方式(参考lox array 的作者博客): /asd.md
            #      - http client and retryable http client: /asd.md
            #      - copier: /asd.md
            #      - singleflight: /asd.md
            #      - serveHTTP , listenAndServe: /asd.md
            #  - Go concurrency programming:
            #      - concurrent read/write map bug: /asd.md
            #  - distributed system:
            #      - etcd: /asd.md
            #      - zk: /asd.md
            #      - spanner
            #  - t100liked
            #  - problem-solve / math
            #      - 3blue1brown - youtube - problem solve



      #  (废弃)
          #      - 数据库选错索引问题一例: too-much-folder/db-wrong-index.md
          # 黑盒查CPU 占用高 QPS 问题
#      - 服务器内存检查手册: too-much-folder/black-box-memory-problem.md
#      - 服务器 CPU 检查手册: too-much-folder/black-box-cpu-problem.md
          #- 网络问题排查的一般思路: too-much-folder/network-problem-general-shooting.md



  - labs:
#      - golox - 过程中遇到和解决了什么问题,如何解决的,学到了什么: asd.md
#      - golox - Scanner: labs/golox/scanner.md
#      - golox - Parser: labs/golox/parser.md
#      - golox - Resolver: labs/golox/resolver.md
#      - golox - Intepreter: labs/golox/interpreter.md
#      - simpledb - HeapFileRead and SeqScan: labs/simpledb/heapfile-read-and-seqscan.md
#      - simpledb - Operators: labs/simpledb/operators.md
#      - simpledb - Query Optimization: labs/simpledb/query-optimization.md
#      - simpledb - Lock Manager and Concurrency Manager: labs/simpledb/lock-and-concurrency.md
#      - xv6 - utils: labs/xv6/utils.md
#      - xv6 - syscall: labs/xv6/syscall.md
      #      - xv6 - page table: labs/xv6/page-table.md
      #- xv6 使用 gdb 调试打印内存布局: asd
      - MIT 6.824 - MapReduce: labs/6824-mapreduce.md
      - MIT 6.824 - Raft: labs/6824-raft.md
      - MIT 6.824 - KV: labs/6824-kv.md
      - CSAPP - Shell: labs/csapp-shell.md
      - CSAPP - Proxy: labs/csapp-proxy.md
#      - beargit: labs/zombie-beargit.md
      - CS144: labs/cs144.md
#      - CS144-lab0: labs/cs144.md
#      - CS144-lab1: labs/cs144.md
#      - CS144-lab2: labs/cs144.md
#      - CS144-lab3: labs/cs144.md
#      - CS144: labs/cs144-lab4-rework.md
#      - CS144: labs/cs144-lab5.md
#      - CS144: labs/cs144-lab6.md
#      - CMU15445-2020: asd.md
#      - CMU 15-445 ClockReplacer: labs/cmu-15445-replacer.md
#      - CMU 15-445 HashTable: labs/cmu-15445-hashtable.md
#      - CMU 15-445 课程回顾: labs/cmu-15445.md
      #      - Staffjoy 总结: labs/staffjoy.md
      #      - Distributed Crontab: labs/distributed-crontab.md
      #      - Talent Plan - TiKV Lab: asdasd
#  - 操作系统 :
      # 其他课上的gdb调试过程
#      - xv6 编译安装,启动: labs/xv6/xv6-install.md
#      - xv6 常用命令: asd.md
#      - xv6 gdb 调试案例: asd.md
#      - xv6 添加用户态程序: asd.md
#      - xv6 排查用户态程序没有 exit 导致的IP 寄存器越界问题: asd.md
#      - xv6 添加系统调用: asd.md   添加系统调用的步骤 , 调试跟着系统调用过程
#      - xv6 启动过程调试: asd.md
#      - xv6 优化 - 在内核态直接 deference 用户态指针: asd.md
#      - xv6 实现用户态 trap 处理: asd.md
#      - xv6 延迟分配用户态内存申请: asd.md
#      - xv6 实现 fork copy on write: asd.md
#      - xv6 实现多线程: asd.md
#      - xv6 优化 memory allocator 和 block cache , 减少锁竞争,提高并行度 (修改数据结构,锁策略): asd.md
#      - xv6 实现 - 支持大文件和符号逻辑: asd.md
#      - xv6 实现 - 支持mmap, 映射文件到地址空间, 和其他进程共享地址空间: asd.md
#      - xv6 实现 - 给 network interface card 写设备驱动: asd.md

  - 工具:
#      - arch linux 安装记录: too-much-folder/arch-linux.md
#      - qemu/kvm 单显卡直通 mac 记录: too-much-folder/single-passthrough.md
      - Xdebug : tools/xdebug.md
      - Chrome Dev Tools : tools/chrome-dev-tools.md
      - Markdown Diagram 功能: tools/markdown-diagram.md
      - yaml lint: too-much-folder/yaml-lint.md
#      - 零散的工具使用技巧: tools/other-tools-usage.md
#      - RabbitMQ: asd.md
  - 算法:
      - 整数转二进制字符串: algos/int-to-binary-str.md
      - 多字段排序: algos/multiple-field-sort.md
      - LRU 线程安全和高并发: algos/lru-cache-go.md
#      - t100-0x-asd: algos/t100-0x-asd.md
#      - 一维数组 parent child 转多维树状数组: asd.md
#      - 抖音那道树题: asd.md
#  - 数学/逻辑:
#      - 和波利亚学解题: problem-solve/learn-problem-solve-with-polya.md
#      - 计数和概率: problem-solve/probability.md
#      - 逻辑: problem-solve/逻辑智力题.md
#  - 构建自己的 X 项目:
#      - 构建自己的 jQuery: build-my-own-x/jquery.md
#        - 构建一个 DB
      #      - 尝试构建一个 Redis: build-my-own-x/redis.md
#      - 构建 Lisp Compiler: build-my-own-x/lisp-compiler.md
#      - Regex Engine 学习: build-my-own-x/regex.md
      #      - 构建自己的 JSON Compiler: asd
#      - 构建自己的 Chip 8 Emulator: asd
      #      - 构建自己的 Vue 框架: build-my-own-x/vue.md
      #      - 构建自己的 HTTP Cache 中间件: build-my-own-x/http-cache-middleman.md
      #      - 自己的 Symfony Lock / UID Component
  #      - 构建自己的 doctrine ORM: build-my-own-x/doctrine-orm.md
  #      - 构建自己的 Timer: build-my-own-x/go-timer.md
  #      - 构建自己的 OS: build-my-own-x/os.md
  #      - 自己的消息队列: asd.md
  - PHP:
      - Composer 是如何工作的: php/how-composer-work.md
      - 业务代码的框架: php/business-logic-framework.md
      - Symfony Lock Component: php/symfony-lock.md
      - 构建自己的 PHP 框架: build-my-own-x/php-framework.md

  - 杂项:
      - Mac Python环境 miniConda 搭建: others/mac_py_env_deploy.md
      - Taylor otwell 采访文章: others/taylor-otwell-interview.md

  - 零碎知识点:
      - 编程技巧/方法: knowledge-reduce/tricks.md
      - 网络编程: knowledge-reduce/network_programming.md
      - 问题排查: knowledge-reduce/problem_trace.md
      - 计算机网络课程分享: knowledge-reduce/network-course.md
      - MYSQL: knowledge-reduce/mysql.md
      - 语言特性/底层实现: knowledge-reduce/language_trait_and_implementation.md
      - 计算机组成原理: knowledge-reduce/computer_composition.md
  #  - 系统设计:
  #      - 秒杀系统设计: asd.md
  - 归档:
      - 博客服务器环境搭建记录: archive/blog_deploy_log.md
      - Redis 设计与实现笔记: redis/redis_code_book_reading.md
      - Laracasts学习记录: archive/laracasts_learning_path.md
      - K480N 黑苹果安装记录: archive/black_sierra.md
      - 从框架看PHP的五种境界[转]: archive/php_career_guide_line.md
      - Laravel中的Marcoable: archive/laravel_marcoable.md
      - Laravel框架关键技术-阅读总结: archive/laravel_code_book_reading.md
      - Laravel-Admin源码阅读: archive/laravel_admin_code_reading.md
      - 实习: archive/first_internship.md
      - 2017 总结: summary/2017.md
      - 2018 总结: archive/second_job.md
      - 2019 总结: summary/2019.md
      - 2020 总结: summary/2020.md


  #  - 问题排查:
  #      - asd: asd
  #  - GO:
  #      - dsad: asd
  #      - sdds: dd
  #      - dsds: ddd
  #  - Redis 源码阅读:
  #      - ASD: asd
  #  - 微服务实践笔记:
  #      - ASD: asd
