site_name: Log0c
nav:
  - 主页: index.md
  - 工具:
      - Xdebug: tools/xdebug.md
      - Chrome Dev Tools: tools/chrome-dev-tools.md
      - Markdown 画图: tools/markdown-diagram.md
  - 算法:
      - 整数转二进制字符串: algos/int-to-binary-str.md
      - 多字段排序: algos/multiple-field-sort.md
      - LRU 线程安全和高并发: algos/lru-cache-go.md
  - 构建自己的 X 项目:
      - 构建自己的 jQuery: build-my-own-x/jquery.md
      - 构建自己的 PHP 框架: build-my-own-x/php-framework.md
#      - 构建自己的 Lisp Compiler: asd
#      - 构建自己的 Regex Engine: asd
#      - 构建自己的 JSON Compiler: asd
#      - 构建自己的 Chip 8 Emulator: asd
#      - 构建自己的 Vue 框架: build-my-own-x/vue.md
#      - 构建自己的 HTTP Cache 中间件: build-my-own-x/http-cache-middleman.md
  - 课程 Labs:
      - CSAPP - Proxy 总结: labs/csapp-proxy.md
      - CSAPP - Shell 总结: labs/csapp-shell.md
  #      - MIT 6.824 - MapReduce: asd
  #      - MIT 6.824 - Raft: asd
  #      - MIT 6.824 - KV: asd
  #      - CS144 - ByteStream: asd
  #      - CS144 - TCP Sender: asd
  #      - CS144 - TCP Receiver: asd
  #      - CS144 - TCP Connection: asd
  - Mac:
      - Notes.app 卡死问题: mac/mac-note-stalled.md
      - 外部 SSD Swap 分区开启问题: mac/osx86_external_ssd_swap_problem.md
  - PHP:
      - Composer 是如何工作的: php/how-composer-work.md
#  - 问题排查:
#      - asd: asd
#  - GO:
#      - dsad: asd
#      - sdds: dd
#      - dsds: ddd
  #  - Redis 源码阅读:
  #      - ASD: asd
  #  - 微服务实践笔记:
  #      - ASD: asd
#  - 杂项:
#      - asd: asd


theme: readthedocs
plugins:
#  - markdownmermaid
  - mermaid2
#extra_javascript:
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js